# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: CCP.EVEOnline
PackageVersion: "2294803"
PackageLocale: en-US
Publisher: CCP Games
PackageName: Eve Online
License: Proprietary
ShortDescription: A space MMORPG sandbox game
ManifestType: defaultLocale
ManifestVersion: 1.5.0
