# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: OrpheusTechnologyLtd.ProWritingAidEverywhere
PackageVersion: 3.2.2563.3
PackageLocale: en-US
Publisher: Orpheus Technology Ltd
PackageName: ProWritingAid Everywhere
License: Proprietary Software
Copyright: Copyright © 2022, Orpheus Technology Ltd
ShortDescription: A desktop grammar and proofreading software
ManifestType: defaultLocale
ManifestVersion: 1.2.0

