# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.2.0.schema.json

PackageIdentifier: OrpheusTechnologyLtd.ProWritingAidEverywhere
PackageVersion: 3.2.2563.3
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.2.0

